name: Documentation improvement
description: Suggest an improvement or report a mistake in the documentation.
labels:
  - 0. Needs triage
body:
  - type: markdown
    attributes:
      value: |
        #### Thank you for helping improve our documentation!
        All contributions - whether large or small - help make Nextcloud better and easier to use.
        
        There is always room for improvement!
        ---
        💡 **Tip:** Make sure you're looking at the latest version of the docs linked from [https://docs.nextcloud.com/](https://docs.nextcloud.com/).
  - type: checkboxes
    id: prechecks
    attributes:
      label: Before You Submit
      options:
        - label: I have checked for existing issues and pull requests related to my suggestion.
        - label: I have posted on the [Nextcloud Help Forum](https://help.nextcloud.com) if my suggestion is a troubleshooting scenario or I'm unsure about the solution.
  - type: dropdown
    id: type
    attributes:
      label: Type of Suggestion
      description: Please select the type that best fits your suggestion.
      options:
        - Reporting a mistake
        - Suggesting an improvement
        - Proposing new documentation content
        - Other
      multiple: true
  - type: input
    id: links
    attributes:
      label: Relevant Documentation Links
      description: Add URLs of relevant documentation pages here.
      placeholder: https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/
  - type: input
    id: summary
    attributes:
      label: Summary
      description: In one sentence, summarize your suggestion or report.
      placeholder: Write your summary here.
  - type: textarea
    id: details
    attributes:
      label: Details
      description: |
        Describe your suggestion or idea in detail. If reporting a mistake, include steps to reproduce or context.
        Example: My amazing idea is [...]
      placeholder: Describe your idea or report in detail.
  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Any extra information, context, or follow-up links (like forum discussions).
      placeholder: Add any additional notes here.
  - type: markdown
    attributes:
      value: |
        ---
        #### Project Guidance

        - Please be patient: this is a large open source project overseen by a mix of volunteers and non-volunteers, and everyone is ultimately busy.
        - If your suggestion is a troubleshooting scenario or something you're not 100% certain about, please post for feedback on the [Nextcloud Help Forum](https://help.nextcloud.com) first.
          - Afterwards, return here to share your experience and help improve the documentation for clarity, etc. (and link back to the forum discussion in your report!)

        #### Pro Tip: Want to help even more?

        - Look for areas where you can assist - even seemingly unrelated areas - as doing so frees up resources for your favorite topics and ideas.
        - Submit a proposed change that addresses your issue as a pull request.
        - Participate in discussions on other unresolved [submitted ideas ("issues")](https://github.com/nextcloud/documentation/issues) to help move them forward.
        - Post a comment or review on someone else's [proposed change ("pull request")](https://github.com/nextcloud/documentation/pulls) to help move it along.

        ---
        Thank you for taking the time to help us make Nextcloud documentation better!
